# Generated by Django 3.1.6 on 2021-02-07 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xmeme', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memepost',
            old_name='meme_url',
            new_name='url',
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xmeme.memepost')),
            ],
        ),
    ]
