# Generated by Django 3.1.6 on 2021-02-08 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xmeme', '0002_auto_20210207_2236'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='HashTags',
        ),
    ]
